### ISSUE TITLE
Linux build?

### ISSUE THREAD

**Issue by s1nka** [mailru/icqdesktop#1]
Where is instruction for linux build?

**Comment by Newlifer** [comment]
+1

**Comment by tonal** [comment]
+1

**Comment by xanderxfz** [comment]
+1

**Comment by Lampus** [comment]
+1

**Comment by reverendhomer** [comment]
+1

**Comment by rzhilkin** [comment]
tnx for reporting, see README.txt

**Comment by a1batross** [comment]
@Newlifer 
oh, familiar faces here too. 

Just -1 here, because it's looks like Mail.Ru just went to the graveyard, dig out the icq's corpse, dismembered it and posted to GitHub story about this. And yeah, rotten entrails too.

**Comment by Newlifer** [comment]
@a1batross So what?

**Comment by Newlifer** [comment]
@rzhilkin thanks!

**Comment by a1batross** [comment]
@Newlifer Mail.Ru's spyware silently installs on Windows machines.
I didn't think that Mail.Ru can be nice someday.

**Comment by reverendhomer** [comment]
@a1batross, can you please turn off your offtopic and flame? This topic 
about porting icq client on Linux, not about Mail.ru at all.

18.03.2016 16:59, Alibek Omarov пишет:
> @Newlifer <https://github.com/Newlifer> Mail.Ru's spyware silently
> installs on Windows machines.
> I didn't think that Mail.Ru can be nice someday.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mailru/icqdesktop/issues/1#issuecomment-198373441>
>

-- 
Regards,
R.H.

**Comment by a1batross** [comment]
@reverendhomer

What's wrong with 3rdparty clients? As I remember, in epoch of ICQ there was a bunch custom clients.

**Comment by reverendhomer** [comment]
@a1batross, this comment is not related to the original post too. Please 
stop.

18.03.2016 17:55, Alibek Omarov пишет:
> @reverendhomer <https://github.com/reverendhomer>
>
> What's wrong with 3rdparty clients? As I remember, in epoch of ICQ there
> was a bunch custom clients.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mailru/icqdesktop/issues/1#issuecomment-198396473>
>

-- 
Regards,
R.H.
