### ISSUE TITLE
Нет просмотра переданной картинки. 

### ISSUE THREAD

**Issue by AlekseyShi** [mailru/icqdesktop#17]
Нет просмотра переданной картинки. Есть только ее сохранить и тогда смотреть. Это неправильно. Хотя в самом чате отображается ее превьюшка.

**Comment by prokofiev88** [comment]
Есть просмотр картинки в чате

**Comment by AlekseyShi** [comment]
ОХ! Да ты прочти что написано то?! В чате превьюшка. Или уменьшенная копия. Оригинала нет! Посмотрите как это работает в Телеграм!

**Comment by rzhilkin** [comment]
Нажимаете на превью лкм - открывается оригинал. Что не так?

**Comment by AlekseyShi** [comment]
на одном компе работает, на другом нет (там картинки открываются в браузере почему-то, поэтому человек сделал вывод что не работает).
на ладно. работает значит. тогда отбой. :)

**Comment by AlekseyShi** [comment]
Не. Не работает. Вот только что вставил в чат картинку. И "рука" не появляется чтобы кликнуть и посмотреть оригинал

**Comment by AlekseyShi** [comment]
А другие картинки в более ранней истории показывает. Может надо приложение перезапустить?

**Comment by AlekseyShi** [comment]
Точно. Перезапустил приложение и курсор "рука" появился, теперь картинку показывает. Значит БАГА это. :)
