### ISSUE TITLE
 Нужен механизм автообновления программы при выходе новых релизов

### ISSUE THREAD

**Issue by AlekseyShi** [mailru/icqdesktop#18]
Нужен механизм автообновления программы при выходе новых релизов. Чтобы пользователь не заморачивался каждый раз заглядывать на сайт и качать новую версию

**Comment by rzhilkin** [comment]
Такой механизм есть, программа обновляется на старте.

**Comment by AlekseyShi** [comment]
У меня контупер работает месяцами, ПО запускается один раз. Я обновление никогда не получу.
