### ISSUE TITLE
Put all required 3rdparty components to repository so it can be easily to compile

### ISSUE THREAD

**Issue by Krakean** [mailru/icqdesktop#3]

**Comment by Goury** [comment]
I disagree

**Comment by maksbotan** [comment]
Please, **please**, _please_ pull all third-party stuff to separate repo. This is not how source code should be organized. This is not how public open-source app should be deployed.
Please do not encourage ignorant distro maintainers who will happily put into their debs or whatever any binary you just give them.
A Linux system should be consistent, shared-linked and without bundling.
I'm willing to make a good conforming Gentoo ebuild for ICQ (as an official Gentoo maintainer), but please de-bundle all third-party things, as it really blows the repo with unrelated crap.

**Comment by rzhilkin** [comment]
We have placed almost all third party libraries in repository, excluding Qt for linux. It is heavily dependent on the machine, on which it was buitd, as Qt hardcodes paths to binary. It can also be easily obtained and compiled by yourself, so we skipped them.
