### ISSUE TITLE
std::bad_cast

### ISSUE THREAD

**Issue by a5w** [mailru/icqdesktop#32]
While trying to install icq on ubuntu 16.04 from terminal, I get this error
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
Aborted (core dumped)

**Comment by yuliym** [comment]
+1
Some issue
ubuntu 16.04 LTS

yulik@R510D:~/Загрузки$ ./icq 
terminate called after throwing an instance of 'std::bad_cast'
  what():  std::bad_cast
Аварийный останов (сделан дамп памяти)

**Comment by rzhilkin** [comment]
thx for reporting. we've already fixed this issue, please use the new version from http://icq.com/linux

**Comment by yuliym** [comment]
Проверил - работает! Очень Вам благодарен!

08.07.2016 12:08, roman zhilkin пишет:
