### ISSUE TITLE
Contact remove does not work

### ISSUE THREAD

**Issue by vit1251** [mailru/icqdesktop#6]
Hello,

Contact remove does not work properly.

    Given open ICQ application
    And logged in into ICQ system as Mike
    And I have contact(s)
        | Name |
        | Alice   |
    When I remove contact(s)
        | Name |
        | Alice   |
    Then No contact(s) still in list on server or on another ICQ instance
        | Name |
        | Alice   | 

Thanx.

**Comment by vit1251** [comment]
Perhaps the problem in updating the list of contacts in another ICQ application instance.

**Comment by rzhilkin** [comment]
so you deleted the contact, and it was removed. what's the problem?

**Comment by vit1251** [comment]
@rzhilkin between two ICQ does not sync contact list. I am remove contact on work and on my home computer already removed user. It look like contact list out of sync.

**Comment by rzhilkin** [comment]
yes, we support this case. what is the other ICQ instance, the same latest ICQ version or a different one?  are you sure that you didn't mix tabs of contact list and recent contacts? anyway, i will report it to QA. thx.

**Comment by vit1251** [comment]
@rzhilkin version is ICQ 2.3 (2016) and ICQ (10.0.12015). i don't mix tabs.

**Comment by rzhilkin** [comment]
it looks like we've already fixed this issue recently. please wait for the next public release. alternatively, you may build it yourself once we upload new source files.

**Comment by vit1251** [comment]
ok, thanx.

2016-03-21 11:58 GMT+03:00 roman zhilkin <notifications@github.com>:

> it looks like we've already fixed this issue recently. please wait for the
> next public release. alternatively, you may build it yourself once we
> upload new source files.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mailru/icqdesktop/issues/6#issuecomment-199182023>
>



-- 
---
Vitold S,                                  Software Engineer
    Mobile: +7 921 3814559,       Site: http://www.vitold.org/
    VoIP: vit1251@sipnet.ru        LinkedIn:
https://ru.linkedin.com/in/vit1251

**Comment by vit1251** [comment]
ok, thanx.
