### ISSUE TITLE
No "Remove contact" item in main menu item

### ISSUE THREAD

**Issue by vit1251** [mailru/icqdesktop#7]
Hello,
I can not found "Remove contact" item in application main menu.
Thanx.

**Comment by rzhilkin** [comment]
you need to switch to the contact list view (second button on the bottom of contact list) and open context menu for the particular contact. you probably use recent view, there is no remove action in it.
BTW, it's more preferable to ask support with this kind of questions.

**Comment by vit1251** [comment]
@rzhilkin oh no... I talk about menu item "Contact" on application main menu. "Information contact ⌘I" but no menu item Remove contact. I use pre-compiile version 2.6

**Comment by rzhilkin** [comment]
apologies, i didn't get it first. we will consider this as a feedback.
